### ISSUE TITLE
Verify the Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/io.github.itprojects.MasVisGtk#2]
If possible, please consider verifying this Flatpak.

Here is more info about verified apps: https://flathub.org/about

**Comment by itprojects** [comment]
Sorry, not possible. However, the application is free and entirely open source, so you have nothing to worry about. The source code has been annotated, if you have specific concerns.

**Comment by AsciiWolf** [comment]
Why is it not possible? You seem to be the developer of the app and its repository is hosted in your account namespace.

**Comment by itprojects** [comment]
> You seem to be the developer of the app and its repository is hosted in your account namespace.

True. Read section "Why are some apps not verified?"

**Comment by AsciiWolf** [comment]
You mean [this one](https://docs.flathub.org/docs/for-users/verification#why-are-some-apps-not-verified)? You just confirmed that you are the developer of this app.

/cc @barthalion

**Comment by barthalion** [comment]
I'm not sure why I'm being cc'ed? It's up to @itprojects to log in at https://flathub.org/ to verify their app.

https://docs.flathub.org/docs/for-app-authors/verification#im-publishing-an-app-on-flathub-how-do-i-get-it-verified

**Comment by AsciiWolf** [comment]
Because I am not sure whether I understand what the problem with the verification of this app is. @itprojects Claimed that it is related to the "Why are some apps not verified?" section from docs, however they also confirmed that they are the original developer of this app. Anyway, I agree that it is up to them to verify it.
